services:
  - type: web
    name: krishn-pdf-qa
    env: python
    plan: free
    buildCommand: chmod +x setup.sh && ./setup.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    disk:
      name: models
      mountPath: /opt/render/.cache
      sizeGB: 10
